const fs = require('fs');
const path = require('path');
const { timestampForFile, userCookiesDir } = require('./workspace');

const BROWSER_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

class BiliClient {
  constructor(sessionProvider) {
    this.sessionProvider = sessionProvider;
  }

  session() {
    return this.sessionProvider();
  }

  async cookieHeader(url = 'https://www.bilibili.com') {
    const cookies = await this.session().cookies.get({ url });
    return cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ');
  }

  async fetchJson(endpoint) {
    const cookie = await this.cookieHeader('https://www.bilibili.com');
    const response = await fetch(endpoint, {
      signal: AbortSignal.timeout(30000),
      headers: {
        cookie,
        referer: 'https://www.bilibili.com/',
        accept: 'application/json, text/plain, */*',
        'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
        'user-agent': BROWSER_USER_AGENT
      }
    });
    const text = await response.text();
    let json;
    try {
      json = JSON.parse(text);
    } catch {
      throw new Error(`Bilibili returned non-JSON: ${text.slice(0, 180)}`);
    }
    if (!response.ok) throw new Error(`HTTP ${response.status}: ${text.slice(0, 180)}`);
    if (json.code !== 0) throw new Error(`Bilibili API ${json.code}: ${json.message || json.msg || 'unknown'}`);
    return json.data;
  }

  async nav() {
    const data = await this.fetchJson('https://api.bilibili.com/x/web-interface/nav');
    return {
      isLogin: Boolean(data.isLogin),
      mid: data.mid,
      name: data.uname,
      face: data.face
    };
  }

  async listFolders(mid) {
    const data = await this.fetchJson(`https://api.bilibili.com/x/v3/fav/folder/created/list-all?up_mid=${encodeURIComponent(mid)}`);
    return (data.list || []).map((folder) => ({
      id: String(folder.id),
      name: folder.title,
      mediaCount: folder.media_count || 0,
      updatedAt: unixToIso(folder.mtime || folder.ctime)
    }));
  }

  async listVideos(folderId, onProgress = () => {}) {
    const videos = [];
    const pageSize = 20;
    for (let page = 1; page <= 200; page += 1) {
      const url = `https://api.bilibili.com/x/v3/fav/resource/list?media_id=${encodeURIComponent(folderId)}&pn=${page}&ps=${pageSize}&keyword=&order=mtime&type=0&tid=0&platform=web`;
      const data = await this.fetchJson(url);
      const list = data.medias || [];
      for (const item of list) videos.push(normalizeVideo(item));
      const hasMore = data.has_more || list.length === pageSize;
      const total = Number(data.info?.media_count || data.info?.mediaCount || 0);
      onProgress({
        page,
        pageSize,
        loaded: videos.length,
        total: total || null,
        progress: total ? Math.min(1, videos.length / total) : null,
        done: !hasMore || list.length === 0
      });
      if (!hasMore || list.length === 0) break;
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
    return videos;
  }

  async exportCookies(userName) {
    const dir = userCookiesDir(userName);
    const file = path.join(dir, `bilibili-cookies-${timestampForFile()}.txt`);
    const cookies = await this.session().cookies.get({});
    const lines = [
      '# Netscape HTTP Cookie File',
      '# Generated by Star Owner. Keep this file private.'
    ];
    for (const cookie of cookies) {
      if (!cookie.domain.includes('bilibili.com')) continue;
      const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
      lines.push([domain, includeSubdomains, cookie.path || '/', secure, expires, cookie.name, cookie.value].join('\t'));
    }
    fs.writeFileSync(file, `${lines.join('\n')}\n`, 'utf8');
    return file;
  }
}

function normalizeVideo(item) {
  return {
    bvid: item.bvid || '',
    aid: item.id || item.aid || '',
    title: item.title || '',
    cover: item.cover || item.pic || '',
    description: item.intro || item.desc || '',
    duration: item.duration || 0,
    owner: item.upper?.name || item.owner?.name || '',
    favoriteAddedAt: unixToIso(item.fav_time || item.mtime),
    publishedAt: unixToIso(item.pubtime || item.ctime),
    url: item.link || (item.bvid ? `https://www.bilibili.com/video/${item.bvid}` : '')
  };
}

function unixToIso(value) {
  const number = Number(value || 0);
  if (!number) return '';
  const milliseconds = number > 1e12 ? number : number * 1000;
  const date = new Date(milliseconds);
  return Number.isNaN(date.getTime()) ? '' : date.toISOString();
}

module.exports = { BiliClient };
